sudo: required

services:
  - docker

before_install:
  - docker login -u $ARTIFACT_REGISTRY_USERNAME -p $ARTIFACT_REGISTRY_PASSWORD

script:
  - docker build -t rbobrovnikov/toolbox-root:latest .

deploy:
  - provider: script
    script: docker push rbobrovnikov/toolbox-root:latest
    skip_cleanup: true
    on:
      all_branches: true
